name: eventhub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.0.13
  share_plus: ^10.0.0
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0  
  firebase_auth: ^5.2.0  
  cloud_firestore: ^5.4.0 
  google_sign_in: ^6.1.1
  google_sign_in_web: ^0.12.4+2
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.0.9
  flutter_dotenv: ^5.1.0
  firebase_analytics: ^11.3.0  
  firebase_crashlytics: ^4.1.0 
  provider: ^6.0.5             
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png  
