name: eventhub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  http: ^1.2.1
  shared_preferences: ^2.0.13
  share_plus: ^10.0.0
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4  # Ensure this works with other Firebase packages
  firebase_auth: ^4.17.5   # These should match the `firebase_core` version
  cloud_firestore: ^4.15.5 
  google_sign_in: ^6.1.1
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.0.9
  flutter_dotenv: ^5.1.0
  firebase_analytics: ^10.6.0  
  firebase_crashlytics: ^3.4.1 
  provider: ^6.0.5             



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png  
